### ISSUE TITLE
MustHaveStaticLogProperty rule is too restrictive

### ISSUE THREAD

**Issue by andreycha** [ChilliCream/thor-analyzer#23]
`MustHaveStaticLogProperty` rule is too restrictive: `Log` can also be a property. For example, in [MSDN article](https://msdn.microsoft.com/en-us/library/dn774985%28v=pandp.20%29.aspx?f=255&MSPPError=-2147217396) it is a property. And by doing so, the rule will correspond to its name, because now it's rather `MustHaveStaticLogField` rule :).

**Comment by rstaib** [comment]
First of all, thank you for helping us making this a better product. Any help is very appreciated. You are absolutely right this rule lacks consistency and did not follow common best practice. So in the first step I will rename the rule to `MustHaveStaticLogFieldOrProperty` in order to prevent breaking changes. In step two (version 2.0.0) I will remove the field completely.

**Comment by andreycha** [comment]
Hi. Thanks for quick response.

> I will remove the field completely

I believe field is also [valid implementation](https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.Tracing/documentation/EventCounterTutorial.md), so I guess you can leave it with `FieldOrProperty`.

**Comment by rstaib** [comment]
Yes, a public field is valid as well but not considered as best practice. That is why we are considering to remove it completely in version 2.0.0. But you are always free to write your own `Rule`s and replace our predefined `Rule`s ;-) cause the analyzer offers the flexibility.
